### ISSUE TITLE
Error when running on CentOS 6.10 x64

### ISSUE THREAD

**Issue by nov3mb3r** [microsoft/avml#10]
Upon running I get the following error
``` 
./avml mem.dmp
thread 'main' panicked at 'invalid range', src/libcore/option.rs:1190:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Aborted (core dumped)
```
Kernel release is 2.6.32-754.30.2.el6.x86_64

**Comment by bmc-msft** [comment]
I am actively investigating this issue.

Can you rerun using `RUST_BACKTRACE=full ./avml mem.dmp`?

**Comment by mbielejeski** [comment]
Not the original reporter but I ran into the same issue on a CentOS 6.10 64 bit VM. (kernel 2.6.32-754.el6.x86_64)
Here is the backtrace.

```bash
$ RUST_BACKTRACE=full ./avml mem.dump
thread 'main' panicked at 'invalid range', src/libcore/option.rs:1190:5
stack backtrace:
   0:           0x5b77f6 - backtrace::backtrace::libunwind::trace::h23eff9b732072ec6
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:           0x5b77f6 - backtrace::backtrace::trace_unsynchronized::he99443e3e043181b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:           0x5b77f6 - std::sys_common::backtrace::_print_fmt::h372c2c133ace10bb
                               at src/libstd/sys_common/backtrace.rs:76
   3:           0x5b77f6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h45d79e0e31af34d1
                               at src/libstd/sys_common/backtrace.rs:60
   4:           0x4a6f5c - core::fmt::write::h6412e51ee7d5337d
                               at src/libcore/fmt/mod.rs:1030
   5:           0x5b7116 - std::io::Write::write_fmt::hc321dd9edd55d777
                               at src/libstd/io/mod.rs:1412
   6:           0x5b6e00 - std::sys_common::backtrace::_print::h308bfa161bac386c
                               at src/libstd/sys_common/backtrace.rs:64
   7:           0x5b6e00 - std::sys_common::backtrace::print::h444e6c0fa7bcde58
                               at src/libstd/sys_common/backtrace.rs:49
   8:           0x5b6e00 - std::panicking::default_hook::{{closure}}::h0556362794d99987
                               at src/libstd/panicking.rs:196
   9:           0x5b676a - std::panicking::default_hook::h9a006f22406ae1a5
                               at src/libstd/panicking.rs:210
  10:           0x5b676a - std::panicking::rust_panic_with_hook::h00181808d6f69bb1
                               at src/libstd/panicking.rs:473
  11:           0x5b62fe - std::panicking::continue_panic_fmt::hd4650be798eb9cfd
                               at src/libstd/panicking.rs:380
  12:           0x5c0906 - rust_begin_unwind
                               at src/libstd/panicking.rs:307
  13:           0x4a4959 - core::panicking::panic_fmt::h6a2a10b60da43dee
                               at src/libcore/panicking.rs:85
  14:           0x4a7686 - core::option::expect_failed::h53ee0d97814b8f6b
                               at src/libcore/option.rs:1190
  15:           0x41d672 - core::option::Option<T>::expect::he0be438802b52b75
  16:           0x401d09 - avml::main::h13066322a5076777
  17:           0x41305e - std::rt::lang_start::{{closure}}::h212053e7f23315d2
  18:           0x405021 - main
Aborted
```

**Comment by bmc-msft** [comment]
Can you paste the results of `cat /proc/iomem`?

**Comment by mbielejeski** [comment]
```bash
$ cat /proc/iomem
00000000-0000ffff : reserved
00010000-0009e7ff : System RAM
0009e800-0009ffff : reserved
000a0000-000bffff : PCI Bus 0000:00
000c0000-000c7fff : Video ROM
000ca000-000cafff : Adapter ROM
000cb000-000ccfff : Adapter ROM
000d0000-000d3fff : PCI Bus 0000:00
000d4000-000d7fff : PCI Bus 0000:00
000d8000-000dbfff : PCI Bus 0000:00
000dc000-000fffff : reserved
  000f0000-000fffff : System ROM
00100000-7fedffff : System RAM
  01000000-015643e4 : Kernel code
  015643e5-01c2384f : Kernel data
  01d80000-02050a63 : Kernel bss
  03000000-0b0fffff : System RAM
7fee0000-7fefefff : ACPI Tables
7feff000-7fefffff : ACPI Non-volatile Storage
7ff00000-7fffffff : System RAM
c0000000-febfffff : PCI Bus 0000:00
  c0000000-c0007fff : 0000:00:0f.0
  c0008000-c000bfff : 0000:00:10.0
  e5b00000-e5bfffff : PCI Bus 0000:22
  e5c00000-e5cfffff : PCI Bus 0000:1a
  e5d00000-e5dfffff : PCI Bus 0000:12
  e5e00000-e5efffff : PCI Bus 0000:0a
  e5f00000-e5ffffff : PCI Bus 0000:21
  e6000000-e60fffff : PCI Bus 0000:19
  e6100000-e61fffff : PCI Bus 0000:11
  e6200000-e62fffff : PCI Bus 0000:09
  e6300000-e63fffff : PCI Bus 0000:20
  e6400000-e64fffff : PCI Bus 0000:18
  e6500000-e65fffff : PCI Bus 0000:10
  e6600000-e66fffff : PCI Bus 0000:08
  e6700000-e67fffff : PCI Bus 0000:1f
  e6800000-e68fffff : PCI Bus 0000:17
  e6900000-e69fffff : PCI Bus 0000:0f
  e6a00000-e6afffff : PCI Bus 0000:07
  e6b00000-e6bfffff : PCI Bus 0000:1e
  e6c00000-e6cfffff : PCI Bus 0000:16
  e6d00000-e6dfffff : PCI Bus 0000:0e
  e6e00000-e6efffff : PCI Bus 0000:06
  e6f00000-e6ffffff : PCI Bus 0000:1d
  e7000000-e70fffff : PCI Bus 0000:15
  e7100000-e71fffff : PCI Bus 0000:0d
  e7200000-e72fffff : PCI Bus 0000:05
  e7300000-e73fffff : PCI Bus 0000:1c
  e7400000-e74fffff : PCI Bus 0000:14
  e7500000-e75fffff : PCI Bus 0000:0c
  e7600000-e76fffff : PCI Bus 0000:04
  e7700000-e77fffff : PCI Bus 0000:1b
  e7800000-e78fffff : PCI Bus 0000:13
  e7900000-e79fffff : PCI Bus 0000:0b
  e7a00000-e7afffff : PCI Bus 0000:03
  e7b00000-e7ffffff : PCI Bus 0000:02
    e7b00000-e7b0ffff : 0000:02:01.0
    e7b10000-e7b1ffff : 0000:02:05.0
  e8000000-efffffff : 0000:00:0f.0
    e8000000-efffffff : vmwgfx probe
  f0000000-f7ffffff : PCI MMCONFIG 0 [00-7f]
    f0000000-f7ffffff : reserved
      f0000000-f7ffffff : pnp 00:0a
  fb500000-fb5fffff : PCI Bus 0000:22
  fb600000-fb6fffff : PCI Bus 0000:1a
  fb700000-fb7fffff : PCI Bus 0000:12
  fb800000-fb8fffff : PCI Bus 0000:0a
  fb900000-fb9fffff : PCI Bus 0000:21
  fba00000-fbafffff : PCI Bus 0000:19
  fbb00000-fbbfffff : PCI Bus 0000:11
  fbc00000-fbcfffff : PCI Bus 0000:09
  fbd00000-fbdfffff : PCI Bus 0000:20
  fbe00000-fbefffff : PCI Bus 0000:18
  fbf00000-fbffffff : PCI Bus 0000:10
  fc000000-fc0fffff : PCI Bus 0000:08
  fc100000-fc1fffff : PCI Bus 0000:1f
  fc200000-fc2fffff : PCI Bus 0000:17
  fc300000-fc3fffff : PCI Bus 0000:0f
  fc400000-fc4fffff : PCI Bus 0000:07
  fc500000-fc5fffff : PCI Bus 0000:1e
  fc600000-fc6fffff : PCI Bus 0000:16
  fc700000-fc7fffff : PCI Bus 0000:0e
  fc800000-fc8fffff : PCI Bus 0000:06
  fc900000-fc9fffff : PCI Bus 0000:1d
  fca00000-fcafffff : PCI Bus 0000:15
  fcb00000-fcbfffff : PCI Bus 0000:0d
  fcc00000-fccfffff : PCI Bus 0000:05
  fcd00000-fcdfffff : PCI Bus 0000:1c
  fce00000-fcefffff : PCI Bus 0000:14
  fcf00000-fcffffff : PCI Bus 0000:0c
  fd000000-fd0fffff : PCI Bus 0000:04
  fd100000-fd1fffff : PCI Bus 0000:1b
  fd200000-fd2fffff : PCI Bus 0000:13
  fd300000-fd3fffff : PCI Bus 0000:0b
  fd400000-fd4fffff : PCI Bus 0000:03
  fd500000-fdffffff : PCI Bus 0000:02
    fd5c0000-fd5dffff : 0000:02:01.0
      fd5c0000-fd5dffff : e1000
    fd5ee000-fd5eefff : 0000:02:05.0
      fd5ee000-fd5eefff : ahci
    fd5ef000-fd5effff : 0000:02:03.0
      fd5ef000-fd5effff : ehci_hcd
    fdff0000-fdffffff : 0000:02:01.0
      fdff0000-fdffffff : e1000
  fe000000-fe7fffff : 0000:00:0f.0
    fe000000-fe7fffff : vmwgfx probe
  fe800000-fe9fffff : pnp 00:0a
  feba0000-febbffff : 0000:00:10.0
    feba0000-febbffff : mpt
  febc0000-febdffff : 0000:00:10.0
    febc0000-febdffff : mpt
  febfe000-febfffff : 0000:00:07.7
fec00000-fec0ffff : reserved
  fec00000-fec003ff : IOAPIC 0
fed00000-fed003ff : HPET 0
  fed00000-fed003ff : pnp 00:08
fee00000-fee00fff : Local APIC
  fee00000-fee00fff : reserved
fffe0000-ffffffff : reserved
```

**Comment by bmc-msft** [comment]
I see the issue and will work on a fix.

**Comment by bmc-msft** [comment]
The kernel you are running splits out "System Ram" into sub-components, which also also included "System Ram" as a type.  This isn't something I've seen before.  

I will have a PR shortly which will address this.

**Comment by bmc-msft** [comment]
@mbielejeski, Release [0.2.1](https://github.com/microsoft/avml/releases/tag/v0.2.1) should address your issue.

**Comment by mbielejeski** [comment]
Thanks for the fast turn around!

I tried it out and can confirm that v0.2.1 fixed the issue.
